// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb-CKoNL_iCuXePaYJUubEvDdpLdpC0g4',
    appId: '1:1022575271504:web:ad29a33c09a7e4b2477b55',
    messagingSenderId: '1022575271504',
    projectId: 'chatappforshalgalt',
    authDomain: 'chatappforshalgalt.firebaseapp.com',
    storageBucket: 'chatappforshalgalt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARO41qSL_tvjyDbKWLRQtIV9uhZEeDC_8',
    appId: '1:1022575271504:android:e5ef0772eb995f01477b55',
    messagingSenderId: '1022575271504',
    projectId: 'chatappforshalgalt',
    storageBucket: 'chatappforshalgalt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCklD1IaFf5fdmCiGr-gwORiNv9NQX_0jM',
    appId: '1:1022575271504:ios:f59bc5fba5e7acc1477b55',
    messagingSenderId: '1022575271504',
    projectId: 'chatappforshalgalt',
    storageBucket: 'chatappforshalgalt.appspot.com',
    iosClientId: '1022575271504-7kok7effhu5af4saddnaqrmse455naud.apps.googleusercontent.com',
    iosBundleId: 'com.example.shalgalt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCklD1IaFf5fdmCiGr-gwORiNv9NQX_0jM',
    appId: '1:1022575271504:ios:f59bc5fba5e7acc1477b55',
    messagingSenderId: '1022575271504',
    projectId: 'chatappforshalgalt',
    storageBucket: 'chatappforshalgalt.appspot.com',
    iosClientId: '1022575271504-7kok7effhu5af4saddnaqrmse455naud.apps.googleusercontent.com',
    iosBundleId: 'com.example.shalgalt',
  );
}
